events {}

http {
    upstream myapp {
        server caddy1;
        server caddy2;
    }

    server {
        listen 88;

        location / {
            proxy_pass http://myapp;
        }
    }
}
